### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aerjayc** [aerjayc/mu-api#1]
# TODO

## Broad

- [x] Series
- [ ] Lists
  - [x] Add Unfinished, Complete, Custom Lists
- [ ] Authors
- [ ] Groups
- [ ] Releases
- [ ] Stats
- [ ] Publishers
- [ ] Genre
- [ ] Categories
- [ ] Search
  - [ ] Basic Search
  - [ ] Advanced Search
- [ ] User (log in, sessions, export own lists)
- [ ] Use javascript to get some stuff that can't be downloaded otherwise
  - [ ] Use javascript to click `More...` to parse the series description completely
- [ ] Tests

## Details

- [x] Use private methods/properties where appropriate
- [x] Export info as json
- [x] Use better date representation
- [ ] Comments detailing the form of the html tags to explain the parsing
- [x] Docstrings (including arguments, return values, exceptions)
- [x] Add error for invalid series id
- [x] Recommendations are sorted by affinity (and _may_ be quantified by the `background-color` assigned to the `<div>`). Try to capture this information
- [ ] Add json-serializable representation of classes so that there's no manual json-ination at the `.json()` methods of those that use those classes
- [ ] Add own user agent
- [ ] Add error handling for connection reset (for when too many requests in a small interval)
- [ ] Allow objects to be pickled
